server:  
  port: ${PORT:8761}
    
eureka:  
  instance:
    hostname: chore-tracker-discovery
  client:
    registerWithEureka: false
    fetchRegistry: false
  server:
    enableSelfPreservation: false